# Generated by Django 2.1.7 on 2020-05-19 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='Body',
            field=models.TextField(default='Enter Text'),
        ),
        migrations.AddField(
            model_name='blog',
            name='publishdate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
